---
# tasks file for ca_server
- name: configure CA server
  ansible.builtin.include_tasks: configure_ca_server.yml

- name: generate certificates for nginx webservers
  ansible.builtin.include_tasks: generate_certificates.yml